### ISSUE TITLE
"/menus forceopen" command doesn't work from console

### ISSUE THREAD

**Issue by PokeSantiTW** [EnvyWare/ForgeMenus#13]
Checking the wiki, this command can also be used in console, but the only message I got is _"You cannot use this command from this source (player only)."_ I think the behavior of the command isn't correct.

**Comment by danorris709** [comment]
Please provide more information

Minecraft version
Mod version
Server software

**Comment by PokeSantiTW** [comment]
Sure!

Minecraft version: 1.12.2 in Magma DEV-v32e7e1a
ForgeMenus version: 2.0.3-1.12.2 _(the latest version)_
Server software: Ubuntu 20.04

Also, I have ForgePlaceholderAPI with ForgePlaceholders, ReforgedPlaceholder and SpigotPlaceholders.

**Comment by danorris709** [comment]
Yeah, you're correct I think I got confused. Will sort out a fix for it in a minute :)

**Comment by danorris709** [comment]
Fixed by 2.0.4
