### ISSUE TITLE
Request code requirement

### ISSUE THREAD

**Issue by GJSteve20** [EnvyWare/ForgeMenus#15]
Mohist doesn't implement any ScriptEngine and code requirement is not working at all. Considering changing the of engine.eval on Mohist.

![image](https://user-images.githubusercontent.com/44862419/166588410-dec5537f-d970-49c9-9431-6c68850e3746.png)

**Comment by danorris709** [comment]
Mohist doesn't implement script engines because it's nothing to do with Mohist. Please stop opening issues when you clearly don't have a clue what you're talking about.
