### ISSUE TITLE
[Update]Request for updating build.gradle to support your latest forge16

### ISSUE THREAD

**Issue by Lileep** [EnvyWare/ForgeMenus#17]
Hi there, I'm trying to learn sth about your 1.16 api from this mod, but when I import it to IDE, it says the project dependency: forge16 need at least gradle 7.1 to build, but the gradle version of this project is still 6.x.
Of course, simply change the gradle version from 6.8.3 to 7.1+ may solve this problem, but I found that there might be sth needs to be edit, too. Like this part:
```gradle
reobf {
    shadowJar {
        classpath = sourceSets.main.compileClasspath
    }
}
```
This part doesn't seem to work in gradle 7.1+. I've seen you removed `classpath = sourceSets.main.compileClasspath` in your project: reforged16, and I put this edits to my project.
But now the shadow plugin of my 1.16 project packs all my dependencies. I have a 1.16 forge project using forge1.16.5-36.2.34, depends on your apis via these codes:
```gradle
    minecraft 'net.minecraftforge:forge:1.16.5-36.2.34'
    shadow group: 'com.github.Pixelmon-Development.API', name: 'commons', version: '2.4.5'
    shadow group: 'com.github.Pixelmon-Development.API', name: 'forge16', version: '2.4.5'
    shadow group: 'com.github.Pixelmon-Development.API', name: 'reforged16', version: '2.4.5'

    //Pixelmon is in an external directory
    implementation fg.deobf('pixelmon:Pixelmon-1.16.5-9.0.0-server:9.0.0')
```

 When I run task `reobfShadowJar`, it shadows dependencies like minecraft and pixelmon, then make a large jar that has 93Mb. I'm at a loss and don't know how to fix it. Have seen sth about the exclude function from shadow doc, but it doesn't work, too. I don't know whether there're connections between the issue and `classpath = sourceSets.main.compileClasspath` statement, so I'd like to ask you about the way of fixing this. It couldn't be better if you could update the build.gradle of this ForgeMenu project or mods that use your reforge16 api, I may learn a lot from those build.gradle files and solve my issue. Thx! :)

**Comment by danorris709** [comment]
This should be fixed in latest
